// S&P 500 Simulation Constants

export const SECTORS = [
	"Technology",
	"Healthcare",
	"Financials",
	"Consumer Discretionary",
	"Communication Services",
	"Industrials",
	"Consumer Staples",
	"Energy",
	"Utilities",
	"Real Estate",
	"Materials",
] as const;

export type Sector = (typeof SECTORS)[number];

export interface TickerConfig {
	symbol: string;
	name: string;
	sector: Sector;
	industry: string;
}

/** 10 tickers for development — top holdings across sectors */
export const DEV_TICKERS: TickerConfig[] = [
	{
		symbol: "AAPL",
		name: "Apple Inc.",
		sector: "Technology",
		industry: "Consumer Electronics",
	},
	{
		symbol: "MSFT",
		name: "Microsoft Corporation",
		sector: "Technology",
		industry: "Software—Infrastructure",
	},
	{
		symbol: "AMZN",
		name: "Amazon.com Inc.",
		sector: "Consumer Discretionary",
		industry: "Internet Retail",
	},
	{
		symbol: "NVDA",
		name: "NVIDIA Corporation",
		sector: "Technology",
		industry: "Semiconductors",
	},
	{
		symbol: "GOOGL",
		name: "Alphabet Inc.",
		sector: "Communication Services",
		industry: "Internet Content & Information",
	},
	{
		symbol: "META",
		name: "Meta Platforms Inc.",
		sector: "Communication Services",
		industry: "Internet Content & Information",
	},
	{
		symbol: "TSLA",
		name: "Tesla Inc.",
		sector: "Consumer Discretionary",
		industry: "Auto Manufacturers",
	},
	{
		symbol: "JPM",
		name: "JPMorgan Chase & Co.",
		sector: "Financials",
		industry: "Banks—Diversified",
	},
	{
		symbol: "UNH",
		name: "UnitedHealth Group Inc.",
		sector: "Healthcare",
		industry: "Healthcare Plans",
	},
	{
		symbol: "V",
		name: "Visa Inc.",
		sector: "Financials",
		industry: "Credit Services",
	},
];

export const SIM_DEFAULTS = {
	symbolCount: 10,
	agentCount: 50,
	activeGroupSize: 10,
	groupCount: 5,
	tickIntervalMs: 1000,
	simulatedTickDuration: 5,
	llmConcurrency: 10,
	llmTimeoutMs: 15000,
	researchFrequency: 20,
	marketMakerRequoteEnabled: true,
	marketMakerMinBookDepth: 2,
	alpacaDataTypes: ["snapshots", "bars"] as string[],
} as const;

/** Full S&P 500 tickers — symbol, name, sector. Switch to this for production scale. */
export const FULL_SP500_TICKERS: {
	symbol: string;
	name: string;
	sector: Sector;
}[] = [
	// Technology
	{ symbol: "AAPL", name: "Apple Inc.", sector: "Technology" },
	{ symbol: "MSFT", name: "Microsoft Corporation", sector: "Technology" },
	{ symbol: "NVDA", name: "NVIDIA Corporation", sector: "Technology" },
	{ symbol: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
	{ symbol: "ORCL", name: "Oracle Corporation", sector: "Technology" },
	{ symbol: "CRM", name: "Salesforce Inc.", sector: "Technology" },
	{ symbol: "AMD", name: "Advanced Micro Devices Inc.", sector: "Technology" },
	{ symbol: "ADBE", name: "Adobe Inc.", sector: "Technology" },
	{ symbol: "ACN", name: "Accenture plc", sector: "Technology" },
	{ symbol: "CSCO", name: "Cisco Systems Inc.", sector: "Technology" },
	{
		symbol: "IBM",
		name: "International Business Machines",
		sector: "Technology",
	},
	{ symbol: "INTC", name: "Intel Corporation", sector: "Technology" },
	{ symbol: "INTU", name: "Intuit Inc.", sector: "Technology" },
	{ symbol: "TXN", name: "Texas Instruments Inc.", sector: "Technology" },
	{ symbol: "QCOM", name: "Qualcomm Inc.", sector: "Technology" },
	{ symbol: "AMAT", name: "Applied Materials Inc.", sector: "Technology" },
	{ symbol: "NOW", name: "ServiceNow Inc.", sector: "Technology" },
	{ symbol: "PANW", name: "Palo Alto Networks Inc.", sector: "Technology" },
	{ symbol: "MU", name: "Micron Technology Inc.", sector: "Technology" },
	{ symbol: "LRCX", name: "Lam Research Corporation", sector: "Technology" },
	{ symbol: "ADI", name: "Analog Devices Inc.", sector: "Technology" },
	{ symbol: "KLAC", name: "KLA Corporation", sector: "Technology" },
	{ symbol: "SNPS", name: "Synopsys Inc.", sector: "Technology" },
	{ symbol: "CDNS", name: "Cadence Design Systems Inc.", sector: "Technology" },
	{ symbol: "CRWD", name: "CrowdStrike Holdings Inc.", sector: "Technology" },
	{ symbol: "MSI", name: "Motorola Solutions Inc.", sector: "Technology" },
	{ symbol: "FTNT", name: "Fortinet Inc.", sector: "Technology" },
	{ symbol: "MCHP", name: "Microchip Technology Inc.", sector: "Technology" },
	{ symbol: "NXPI", name: "NXP Semiconductors N.V.", sector: "Technology" },
	{ symbol: "ON", name: "ON Semiconductor Corporation", sector: "Technology" },
	{ symbol: "HPQ", name: "HP Inc.", sector: "Technology" },
	{ symbol: "HPE", name: "Hewlett Packard Enterprise", sector: "Technology" },
	{ symbol: "KEYS", name: "Keysight Technologies Inc.", sector: "Technology" },
	{ symbol: "CDW", name: "CDW Corporation", sector: "Technology" },
	{
		symbol: "MPWR",
		name: "Monolithic Power Systems Inc.",
		sector: "Technology",
	},
	{ symbol: "FSLR", name: "First Solar Inc.", sector: "Technology" },
	{ symbol: "ROP", name: "Roper Technologies Inc.", sector: "Technology" },
	{ symbol: "IT", name: "Gartner Inc.", sector: "Technology" },
	{ symbol: "ANSS", name: "ANSYS Inc.", sector: "Technology" },
	{ symbol: "TYL", name: "Tyler Technologies Inc.", sector: "Technology" },
	{
		symbol: "ZBRA",
		name: "Zebra Technologies Corporation",
		sector: "Technology",
	},
	{ symbol: "TER", name: "Teradyne Inc.", sector: "Technology" },
	{ symbol: "TRMB", name: "Trimble Inc.", sector: "Technology" },
	{ symbol: "PTC", name: "PTC Inc.", sector: "Technology" },
	{ symbol: "VRSN", name: "VeriSign Inc.", sector: "Technology" },
	{ symbol: "SWKS", name: "Skyworks Solutions Inc.", sector: "Technology" },
	{ symbol: "GEN", name: "Gen Digital Inc.", sector: "Technology" },
	{ symbol: "EPAM", name: "EPAM Systems Inc.", sector: "Technology" },
	{ symbol: "JNPR", name: "Juniper Networks Inc.", sector: "Technology" },
	{ symbol: "FFIV", name: "F5 Inc.", sector: "Technology" },
	// Healthcare
	{ symbol: "UNH", name: "UnitedHealth Group Inc.", sector: "Healthcare" },
	{ symbol: "LLY", name: "Eli Lilly and Company", sector: "Healthcare" },
	{ symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
	{ symbol: "ABBV", name: "AbbVie Inc.", sector: "Healthcare" },
	{ symbol: "MRK", name: "Merck & Co. Inc.", sector: "Healthcare" },
	{
		symbol: "TMO",
		name: "Thermo Fisher Scientific Inc.",
		sector: "Healthcare",
	},
	{ symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare" },
	{ symbol: "DHR", name: "Danaher Corporation", sector: "Healthcare" },
	{ symbol: "PFE", name: "Pfizer Inc.", sector: "Healthcare" },
	{ symbol: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
	{ symbol: "BMY", name: "Bristol-Myers Squibb Company", sector: "Healthcare" },
	{ symbol: "ISRG", name: "Intuitive Surgical Inc.", sector: "Healthcare" },
	{ symbol: "SYK", name: "Stryker Corporation", sector: "Healthcare" },
	{ symbol: "VRTX", name: "Vertex Pharmaceuticals Inc.", sector: "Healthcare" },
	{ symbol: "MDT", name: "Medtronic plc", sector: "Healthcare" },
	{ symbol: "GILD", name: "Gilead Sciences Inc.", sector: "Healthcare" },
	{
		symbol: "REGN",
		name: "Regeneron Pharmaceuticals Inc.",
		sector: "Healthcare",
	},
	{ symbol: "CI", name: "The Cigna Group", sector: "Healthcare" },
	{ symbol: "ELV", name: "Elevance Health Inc.", sector: "Healthcare" },
	{
		symbol: "BSX",
		name: "Boston Scientific Corporation",
		sector: "Healthcare",
	},
	{ symbol: "HCA", name: "HCA Healthcare Inc.", sector: "Healthcare" },
	{ symbol: "ZTS", name: "Zoetis Inc.", sector: "Healthcare" },
	{ symbol: "MCK", name: "McKesson Corporation", sector: "Healthcare" },
	{ symbol: "BDX", name: "Becton Dickinson and Company", sector: "Healthcare" },
	{
		symbol: "EW",
		name: "Edwards Lifesciences Corporation",
		sector: "Healthcare",
	},
	{ symbol: "A", name: "Agilent Technologies Inc.", sector: "Healthcare" },
	{ symbol: "IQV", name: "IQVIA Holdings Inc.", sector: "Healthcare" },
	{ symbol: "IDXX", name: "IDEXX Laboratories Inc.", sector: "Healthcare" },
	{ symbol: "MTD", name: "Mettler-Toledo International", sector: "Healthcare" },
	{ symbol: "CAH", name: "Cardinal Health Inc.", sector: "Healthcare" },
	{ symbol: "COR", name: "Cencora Inc.", sector: "Healthcare" },
	{ symbol: "GEHC", name: "GE HealthCare Technologies", sector: "Healthcare" },
	{ symbol: "RMD", name: "ResMed Inc.", sector: "Healthcare" },
	{ symbol: "DXCM", name: "DexCom Inc.", sector: "Healthcare" },
	{ symbol: "WST", name: "West Pharmaceutical Services", sector: "Healthcare" },
	{ symbol: "BAX", name: "Baxter International Inc.", sector: "Healthcare" },
	{ symbol: "ZBH", name: "Zimmer Biomet Holdings Inc.", sector: "Healthcare" },
	{ symbol: "ALGN", name: "Align Technology Inc.", sector: "Healthcare" },
	{ symbol: "HOLX", name: "Hologic Inc.", sector: "Healthcare" },
	{ symbol: "PODD", name: "Insulet Corporation", sector: "Healthcare" },
	{ symbol: "RVTY", name: "Revvity Inc.", sector: "Healthcare" },
	{ symbol: "TECH", name: "Bio-Techne Corporation", sector: "Healthcare" },
	{ symbol: "INCY", name: "Incyte Corporation", sector: "Healthcare" },
	{ symbol: "MOH", name: "Molina Healthcare Inc.", sector: "Healthcare" },
	{ symbol: "CNC", name: "Centene Corporation", sector: "Healthcare" },
	{ symbol: "HUM", name: "Humana Inc.", sector: "Healthcare" },
	{ symbol: "BIIB", name: "Biogen Inc.", sector: "Healthcare" },
	{ symbol: "MRNA", name: "Moderna Inc.", sector: "Healthcare" },
	{ symbol: "LH", name: "Labcorp Holdings Inc.", sector: "Healthcare" },
	{ symbol: "DGX", name: "Quest Diagnostics Inc.", sector: "Healthcare" },
	{ symbol: "VTRS", name: "Viatris Inc.", sector: "Healthcare" },
	{ symbol: "XRAY", name: "DENTSPLY SIRONA Inc.", sector: "Healthcare" },
	{ symbol: "DVA", name: "DaVita Inc.", sector: "Healthcare" },
	// Financials
	{ symbol: "JPM", name: "JPMorgan Chase & Co.", sector: "Financials" },
	{ symbol: "V", name: "Visa Inc.", sector: "Financials" },
	{ symbol: "MA", name: "Mastercard Inc.", sector: "Financials" },
	{ symbol: "BAC", name: "Bank of America Corporation", sector: "Financials" },
	{ symbol: "WFC", name: "Wells Fargo & Company", sector: "Financials" },
	{ symbol: "GS", name: "The Goldman Sachs Group Inc.", sector: "Financials" },
	{ symbol: "MS", name: "Morgan Stanley", sector: "Financials" },
	{ symbol: "SPGI", name: "S&P Global Inc.", sector: "Financials" },
	{ symbol: "BLK", name: "BlackRock Inc.", sector: "Financials" },
	{ symbol: "AXP", name: "American Express Company", sector: "Financials" },
	{ symbol: "C", name: "Citigroup Inc.", sector: "Financials" },
	{ symbol: "SCHW", name: "Charles Schwab Corporation", sector: "Financials" },
	{ symbol: "CB", name: "Chubb Limited", sector: "Financials" },
	{ symbol: "PGR", name: "The Progressive Corporation", sector: "Financials" },
	{ symbol: "MMC", name: "Marsh & McLennan Companies", sector: "Financials" },
	{
		symbol: "ICE",
		name: "Intercontinental Exchange Inc.",
		sector: "Financials",
	},
	{ symbol: "CME", name: "CME Group Inc.", sector: "Financials" },
	{ symbol: "AON", name: "Aon plc", sector: "Financials" },
	{ symbol: "MCO", name: "Moody's Corporation", sector: "Financials" },
	{ symbol: "USB", name: "U.S. Bancorp", sector: "Financials" },
	{ symbol: "PNC", name: "PNC Financial Services Group", sector: "Financials" },
	{ symbol: "TFC", name: "Truist Financial Corporation", sector: "Financials" },
	{ symbol: "AIG", name: "American International Group", sector: "Financials" },
	{ symbol: "AFL", name: "Aflac Inc.", sector: "Financials" },
	{ symbol: "MET", name: "MetLife Inc.", sector: "Financials" },
	{ symbol: "PRU", name: "Prudential Financial Inc.", sector: "Financials" },
	{ symbol: "ALL", name: "The Allstate Corporation", sector: "Financials" },
	{ symbol: "TRV", name: "The Travelers Companies Inc.", sector: "Financials" },
	{ symbol: "AJG", name: "Arthur J. Gallagher & Co.", sector: "Financials" },
	{ symbol: "MSCI", name: "MSCI Inc.", sector: "Financials" },
	{ symbol: "BK", name: "The Bank of New York Mellon", sector: "Financials" },
	{ symbol: "COF", name: "Capital One Financial Corp.", sector: "Financials" },
	{ symbol: "STT", name: "State Street Corporation", sector: "Financials" },
	{ symbol: "FITB", name: "Fifth Third Bancorp", sector: "Financials" },
	{ symbol: "DFS", name: "Discover Financial Services", sector: "Financials" },
	{ symbol: "HBAN", name: "Huntington Bancshares Inc.", sector: "Financials" },
	{ symbol: "MTB", name: "M&T Bank Corporation", sector: "Financials" },
	{ symbol: "RF", name: "Regions Financial Corporation", sector: "Financials" },
	{ symbol: "KEY", name: "KeyCorp", sector: "Financials" },
	{
		symbol: "CFG",
		name: "Citizens Financial Group Inc.",
		sector: "Financials",
	},
	{ symbol: "NTRS", name: "Northern Trust Corporation", sector: "Financials" },
	{ symbol: "CINF", name: "Cincinnati Financial Corp.", sector: "Financials" },
	{ symbol: "NDAQ", name: "Nasdaq Inc.", sector: "Financials" },
	{ symbol: "CBOE", name: "Cboe Global Markets Inc.", sector: "Financials" },
	{
		symbol: "FDS",
		name: "FactSet Research Systems Inc.",
		sector: "Financials",
	},
	{ symbol: "WRB", name: "W. R. Berkley Corporation", sector: "Financials" },
	{ symbol: "RJF", name: "Raymond James Financial Inc.", sector: "Financials" },
	{ symbol: "L", name: "Loews Corporation", sector: "Financials" },
	{ symbol: "RE", name: "Everest Group Ltd.", sector: "Financials" },
	{ symbol: "BRO", name: "Brown & Brown Inc.", sector: "Financials" },
	{ symbol: "GL", name: "Globe Life Inc.", sector: "Financials" },
	// Consumer Discretionary
	{ symbol: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary" },
	{ symbol: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary" },
	{
		symbol: "HD",
		name: "The Home Depot Inc.",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "MCD",
		name: "McDonald's Corporation",
		sector: "Consumer Discretionary",
	},
	{ symbol: "NKE", name: "NIKE Inc.", sector: "Consumer Discretionary" },
	{
		symbol: "LOW",
		name: "Lowe's Companies Inc.",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "BKNG",
		name: "Booking Holdings Inc.",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "SBUX",
		name: "Starbucks Corporation",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "TJX",
		name: "The TJX Companies Inc.",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "CMG",
		name: "Chipotle Mexican Grill Inc.",
		sector: "Consumer Discretionary",
	},
	{ symbol: "ABNB", name: "Airbnb Inc.", sector: "Consumer Discretionary" },
	{
		symbol: "ORLY",
		name: "O'Reilly Automotive Inc.",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "MAR",
		name: "Marriott International Inc.",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "HLT",
		name: "Hilton Worldwide Holdings",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "GM",
		name: "General Motors Company",
		sector: "Consumer Discretionary",
	},
	{ symbol: "F", name: "Ford Motor Company", sector: "Consumer Discretionary" },
	{ symbol: "AZO", name: "AutoZone Inc.", sector: "Consumer Discretionary" },
	{
		symbol: "ROST",
		name: "Ross Stores Inc.",
		sector: "Consumer Discretionary",
	},
	{ symbol: "DHI", name: "D.R. Horton Inc.", sector: "Consumer Discretionary" },
	{
		symbol: "LEN",
		name: "Lennar Corporation",
		sector: "Consumer Discretionary",
	},
	{ symbol: "YUM", name: "Yum! Brands Inc.", sector: "Consumer Discretionary" },
	{ symbol: "DASH", name: "DoorDash Inc.", sector: "Consumer Discretionary" },
	{
		symbol: "RCL",
		name: "Royal Caribbean Cruises Ltd.",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "CCL",
		name: "Carnival Corporation",
		sector: "Consumer Discretionary",
	},
	{ symbol: "DKNG", name: "DraftKings Inc.", sector: "Consumer Discretionary" },
	{ symbol: "EBAY", name: "eBay Inc.", sector: "Consumer Discretionary" },
	{
		symbol: "GPC",
		name: "Genuine Parts Company",
		sector: "Consumer Discretionary",
	},
	{ symbol: "PHM", name: "PulteGroup Inc.", sector: "Consumer Discretionary" },
	{ symbol: "NVR", name: "NVR Inc.", sector: "Consumer Discretionary" },
	{
		symbol: "DECK",
		name: "Deckers Outdoor Corporation",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "ULTA",
		name: "Ulta Beauty Inc.",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "DPZ",
		name: "Domino's Pizza Inc.",
		sector: "Consumer Discretionary",
	},
	{ symbol: "APTV", name: "Aptiv PLC", sector: "Consumer Discretionary" },
	{
		symbol: "POOL",
		name: "Pool Corporation",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "BBY",
		name: "Best Buy Co. Inc.",
		sector: "Consumer Discretionary",
	},
	{ symbol: "GRMN", name: "Garmin Ltd.", sector: "Consumer Discretionary" },
	{
		symbol: "EXPE",
		name: "Expedia Group Inc.",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "LVS",
		name: "Las Vegas Sands Corp.",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "MGM",
		name: "MGM Resorts International",
		sector: "Consumer Discretionary",
	},
	{
		symbol: "WYNN",
		name: "Wynn Resorts Limited",
		sector: "Consumer Discretionary",
	},
	{ symbol: "TPR", name: "Tapestry Inc.", sector: "Consumer Discretionary" },
	{
		symbol: "RL",
		name: "Ralph Lauren Corporation",
		sector: "Consumer Discretionary",
	},
	{ symbol: "BWA", name: "BorgWarner Inc.", sector: "Consumer Discretionary" },
	{
		symbol: "CZR",
		name: "Caesars Entertainment Inc.",
		sector: "Consumer Discretionary",
	},
	{ symbol: "HAS", name: "Hasbro Inc.", sector: "Consumer Discretionary" },
	{
		symbol: "MHK",
		name: "Mohawk Industries Inc.",
		sector: "Consumer Discretionary",
	},
	// Communication Services
	{
		symbol: "GOOGL",
		name: "Alphabet Inc. (Class A)",
		sector: "Communication Services",
	},
	{
		symbol: "GOOG",
		name: "Alphabet Inc. (Class C)",
		sector: "Communication Services",
	},
	{
		symbol: "META",
		name: "Meta Platforms Inc.",
		sector: "Communication Services",
	},
	{ symbol: "NFLX", name: "Netflix Inc.", sector: "Communication Services" },
	{
		symbol: "DIS",
		name: "The Walt Disney Company",
		sector: "Communication Services",
	},
	{
		symbol: "CMCSA",
		name: "Comcast Corporation",
		sector: "Communication Services",
	},
	{ symbol: "T", name: "AT&T Inc.", sector: "Communication Services" },
	{
		symbol: "VZ",
		name: "Verizon Communications Inc.",
		sector: "Communication Services",
	},
	{
		symbol: "TMUS",
		name: "T-Mobile US Inc.",
		sector: "Communication Services",
	},
	{
		symbol: "CHTR",
		name: "Charter Communications Inc.",
		sector: "Communication Services",
	},
	{
		symbol: "EA",
		name: "Electronic Arts Inc.",
		sector: "Communication Services",
	},
	{
		symbol: "TTWO",
		name: "Take-Two Interactive Software",
		sector: "Communication Services",
	},
	{
		symbol: "WBD",
		name: "Warner Bros. Discovery Inc.",
		sector: "Communication Services",
	},
	{
		symbol: "OMC",
		name: "Omnicom Group Inc.",
		sector: "Communication Services",
	},
	{
		symbol: "IPG",
		name: "Interpublic Group of Companies",
		sector: "Communication Services",
	},
	{
		symbol: "MTCH",
		name: "Match Group Inc.",
		sector: "Communication Services",
	},
	{
		symbol: "LYV",
		name: "Live Nation Entertainment Inc.",
		sector: "Communication Services",
	},
	{
		symbol: "PARA",
		name: "Paramount Global",
		sector: "Communication Services",
	},
	{
		symbol: "FOXA",
		name: "Fox Corporation (Class A)",
		sector: "Communication Services",
	},
	{ symbol: "NWS", name: "News Corporation", sector: "Communication Services" },
	// Industrials
	{ symbol: "GE", name: "GE Aerospace", sector: "Industrials" },
	{ symbol: "CAT", name: "Caterpillar Inc.", sector: "Industrials" },
	{ symbol: "RTX", name: "RTX Corporation", sector: "Industrials" },
	{ symbol: "UNP", name: "Union Pacific Corporation", sector: "Industrials" },
	{
		symbol: "HON",
		name: "Honeywell International Inc.",
		sector: "Industrials",
	},
	{ symbol: "BA", name: "The Boeing Company", sector: "Industrials" },
	{ symbol: "DE", name: "Deere & Company", sector: "Industrials" },
	{ symbol: "LMT", name: "Lockheed Martin Corporation", sector: "Industrials" },
	{ symbol: "UPS", name: "United Parcel Service Inc.", sector: "Industrials" },
	{
		symbol: "ADP",
		name: "Automatic Data Processing Inc.",
		sector: "Industrials",
	},
	{ symbol: "ETN", name: "Eaton Corporation plc", sector: "Industrials" },
	{ symbol: "WM", name: "Waste Management Inc.", sector: "Industrials" },
	{ symbol: "ITW", name: "Illinois Tool Works Inc.", sector: "Industrials" },
	{
		symbol: "NOC",
		name: "Northrop Grumman Corporation",
		sector: "Industrials",
	},
	{ symbol: "GD", name: "General Dynamics Corporation", sector: "Industrials" },
	{ symbol: "EMR", name: "Emerson Electric Co.", sector: "Industrials" },
	{ symbol: "FDX", name: "FedEx Corporation", sector: "Industrials" },
	{ symbol: "CSX", name: "CSX Corporation", sector: "Industrials" },
	{
		symbol: "NSC",
		name: "Norfolk Southern Corporation",
		sector: "Industrials",
	},
	{ symbol: "PH", name: "Parker-Hannifin Corporation", sector: "Industrials" },
	{ symbol: "CTAS", name: "Cintas Corporation", sector: "Industrials" },
	{ symbol: "TT", name: "Trane Technologies plc", sector: "Industrials" },
	{ symbol: "CARR", name: "Carrier Global Corporation", sector: "Industrials" },
	{ symbol: "MMM", name: "3M Company", sector: "Industrials" },
	{ symbol: "PCAR", name: "PACCAR Inc.", sector: "Industrials" },
	{ symbol: "CPRT", name: "Copart Inc.", sector: "Industrials" },
	{ symbol: "FAST", name: "Fastenal Company", sector: "Industrials" },
	{
		symbol: "JCI",
		name: "Johnson Controls International",
		sector: "Industrials",
	},
	{ symbol: "OTIS", name: "Otis Worldwide Corporation", sector: "Industrials" },
	{ symbol: "AME", name: "AMETEK Inc.", sector: "Industrials" },
	{ symbol: "RSG", name: "Republic Services Inc.", sector: "Industrials" },
	{ symbol: "VRSK", name: "Verisk Analytics Inc.", sector: "Industrials" },
	{ symbol: "GWW", name: "W.W. Grainger Inc.", sector: "Industrials" },
	{ symbol: "PWR", name: "Quanta Services Inc.", sector: "Industrials" },
	{ symbol: "HWM", name: "Howmet Aerospace Inc.", sector: "Industrials" },
	{ symbol: "AXON", name: "Axon Enterprise Inc.", sector: "Industrials" },
	{ symbol: "WAB", name: "Westinghouse Air Brake", sector: "Industrials" },
	{ symbol: "IR", name: "Ingersoll Rand Inc.", sector: "Industrials" },
	{ symbol: "ROK", name: "Rockwell Automation Inc.", sector: "Industrials" },
	{ symbol: "DOV", name: "Dover Corporation", sector: "Industrials" },
	{ symbol: "XYL", name: "Xylem Inc.", sector: "Industrials" },
	{ symbol: "HUBB", name: "Hubbell Inc.", sector: "Industrials" },
	{ symbol: "SWK", name: "Stanley Black & Decker Inc.", sector: "Industrials" },
	{ symbol: "IEX", name: "IDEX Corporation", sector: "Industrials" },
	{ symbol: "DAL", name: "Delta Air Lines Inc.", sector: "Industrials" },
	{
		symbol: "UAL",
		name: "United Airlines Holdings Inc.",
		sector: "Industrials",
	},
	{ symbol: "LUV", name: "Southwest Airlines Co.", sector: "Industrials" },
	{ symbol: "LDOS", name: "Leidos Holdings Inc.", sector: "Industrials" },
	{ symbol: "J", name: "Jacobs Solutions Inc.", sector: "Industrials" },
	{ symbol: "PAYC", name: "Paycom Software Inc.", sector: "Industrials" },
	{ symbol: "EFX", name: "Equifax Inc.", sector: "Industrials" },
	// Consumer Staples
	{
		symbol: "PG",
		name: "Procter & Gamble Company",
		sector: "Consumer Staples",
	},
	{ symbol: "KO", name: "The Coca-Cola Company", sector: "Consumer Staples" },
	{ symbol: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples" },
	{
		symbol: "COST",
		name: "Costco Wholesale Corporation",
		sector: "Consumer Staples",
	},
	{ symbol: "WMT", name: "Walmart Inc.", sector: "Consumer Staples" },
	{
		symbol: "PM",
		name: "Philip Morris International",
		sector: "Consumer Staples",
	},
	{ symbol: "MO", name: "Altria Group Inc.", sector: "Consumer Staples" },
	{
		symbol: "MDLZ",
		name: "Mondelez International Inc.",
		sector: "Consumer Staples",
	},
	{
		symbol: "CL",
		name: "Colgate-Palmolive Company",
		sector: "Consumer Staples",
	},
	{ symbol: "TGT", name: "Target Corporation", sector: "Consumer Staples" },
	{
		symbol: "ADM",
		name: "Archer-Daniels-Midland Company",
		sector: "Consumer Staples",
	},
	{ symbol: "SYY", name: "Sysco Corporation", sector: "Consumer Staples" },
	{
		symbol: "KMB",
		name: "Kimberly-Clark Corporation",
		sector: "Consumer Staples",
	},
	{ symbol: "GIS", name: "General Mills Inc.", sector: "Consumer Staples" },
	{
		symbol: "STZ",
		name: "Constellation Brands Inc.",
		sector: "Consumer Staples",
	},
	{ symbol: "HSY", name: "The Hershey Company", sector: "Consumer Staples" },
	{ symbol: "KDP", name: "Keurig Dr Pepper Inc.", sector: "Consumer Staples" },
	{ symbol: "KR", name: "The Kroger Co.", sector: "Consumer Staples" },
	{
		symbol: "MNST",
		name: "Monster Beverage Corporation",
		sector: "Consumer Staples",
	},
	{
		symbol: "EL",
		name: "The Estée Lauder Companies",
		sector: "Consumer Staples",
	},
	{ symbol: "K", name: "Kellanova", sector: "Consumer Staples" },
	{
		symbol: "CHD",
		name: "Church & Dwight Co. Inc.",
		sector: "Consumer Staples",
	},
	{
		symbol: "MKC",
		name: "McCormick & Company Inc.",
		sector: "Consumer Staples",
	},
	{ symbol: "CLX", name: "The Clorox Company", sector: "Consumer Staples" },
	{
		symbol: "SJM",
		name: "The J.M. Smucker Company",
		sector: "Consumer Staples",
	},
	{ symbol: "CAG", name: "Conagra Brands Inc.", sector: "Consumer Staples" },
	{
		symbol: "HRL",
		name: "Hormel Foods Corporation",
		sector: "Consumer Staples",
	},
	{ symbol: "TSN", name: "Tyson Foods Inc.", sector: "Consumer Staples" },
	{ symbol: "BG", name: "Bunge Global SA", sector: "Consumer Staples" },
	{
		symbol: "TAP",
		name: "Molson Coors Beverage Company",
		sector: "Consumer Staples",
	},
	{
		symbol: "LW",
		name: "Lamb Weston Holdings Inc.",
		sector: "Consumer Staples",
	},
	{ symbol: "CPB", name: "Campbell Soup Company", sector: "Consumer Staples" },
	// Energy
	{ symbol: "XOM", name: "Exxon Mobil Corporation", sector: "Energy" },
	{ symbol: "CVX", name: "Chevron Corporation", sector: "Energy" },
	{ symbol: "COP", name: "ConocoPhillips", sector: "Energy" },
	{ symbol: "EOG", name: "EOG Resources Inc.", sector: "Energy" },
	{ symbol: "SLB", name: "Schlumberger Limited", sector: "Energy" },
	{ symbol: "MPC", name: "Marathon Petroleum Corporation", sector: "Energy" },
	{ symbol: "PXD", name: "Pioneer Natural Resources", sector: "Energy" },
	{ symbol: "PSX", name: "Phillips 66", sector: "Energy" },
	{ symbol: "VLO", name: "Valero Energy Corporation", sector: "Energy" },
	{ symbol: "WMB", name: "The Williams Companies Inc.", sector: "Energy" },
	{ symbol: "OKE", name: "ONEOK Inc.", sector: "Energy" },
	{ symbol: "KMI", name: "Kinder Morgan Inc.", sector: "Energy" },
	{ symbol: "HES", name: "Hess Corporation", sector: "Energy" },
	{ symbol: "HAL", name: "Halliburton Company", sector: "Energy" },
	{ symbol: "DVN", name: "Devon Energy Corporation", sector: "Energy" },
	{ symbol: "FANG", name: "Diamondback Energy Inc.", sector: "Energy" },
	{ symbol: "BKR", name: "Baker Hughes Company", sector: "Energy" },
	{ symbol: "TRGP", name: "Targa Resources Corp.", sector: "Energy" },
	{ symbol: "OXY", name: "Occidental Petroleum Corp.", sector: "Energy" },
	{ symbol: "CTRA", name: "Coterra Energy Inc.", sector: "Energy" },
	{ symbol: "MRO", name: "Marathon Oil Corporation", sector: "Energy" },
	{ symbol: "APA", name: "APA Corporation", sector: "Energy" },
	// Utilities
	{ symbol: "NEE", name: "NextEra Energy Inc.", sector: "Utilities" },
	{ symbol: "SO", name: "The Southern Company", sector: "Utilities" },
	{ symbol: "DUK", name: "Duke Energy Corporation", sector: "Utilities" },
	{ symbol: "CEG", name: "Constellation Energy Corp.", sector: "Utilities" },
	{ symbol: "SRE", name: "Sempra", sector: "Utilities" },
	{ symbol: "AEP", name: "American Electric Power Co.", sector: "Utilities" },
	{ symbol: "D", name: "Dominion Energy Inc.", sector: "Utilities" },
	{ symbol: "PCG", name: "PG&E Corporation", sector: "Utilities" },
	{ symbol: "EXC", name: "Exelon Corporation", sector: "Utilities" },
	{ symbol: "XEL", name: "Xcel Energy Inc.", sector: "Utilities" },
	{ symbol: "ED", name: "Consolidated Edison Inc.", sector: "Utilities" },
	{ symbol: "WEC", name: "WEC Energy Group Inc.", sector: "Utilities" },
	{ symbol: "EIX", name: "Edison International", sector: "Utilities" },
	{ symbol: "AWK", name: "American Water Works Co.", sector: "Utilities" },
	{ symbol: "DTE", name: "DTE Energy Company", sector: "Utilities" },
	{ symbol: "ETR", name: "Entergy Corporation", sector: "Utilities" },
	{ symbol: "PPL", name: "PPL Corporation", sector: "Utilities" },
	{ symbol: "FE", name: "FirstEnergy Corp.", sector: "Utilities" },
	{ symbol: "AEE", name: "Ameren Corporation", sector: "Utilities" },
	{ symbol: "CMS", name: "CMS Energy Corporation", sector: "Utilities" },
	{ symbol: "ES", name: "Eversource Energy", sector: "Utilities" },
	{ symbol: "ATO", name: "Atmos Energy Corporation", sector: "Utilities" },
	{ symbol: "CNP", name: "CenterPoint Energy Inc.", sector: "Utilities" },
	{ symbol: "NI", name: "NiSource Inc.", sector: "Utilities" },
	{ symbol: "EVRG", name: "Evergy Inc.", sector: "Utilities" },
	{ symbol: "LNT", name: "Alliant Energy Corporation", sector: "Utilities" },
	{ symbol: "PNW", name: "Pinnacle West Capital Corp.", sector: "Utilities" },
	// Real Estate
	{ symbol: "PLD", name: "Prologis Inc.", sector: "Real Estate" },
	{ symbol: "AMT", name: "American Tower Corporation", sector: "Real Estate" },
	{ symbol: "EQIX", name: "Equinix Inc.", sector: "Real Estate" },
	{ symbol: "CCI", name: "Crown Castle Inc.", sector: "Real Estate" },
	{ symbol: "PSA", name: "Public Storage", sector: "Real Estate" },
	{ symbol: "SPG", name: "Simon Property Group Inc.", sector: "Real Estate" },
	{ symbol: "O", name: "Realty Income Corporation", sector: "Real Estate" },
	{ symbol: "WELL", name: "Welltower Inc.", sector: "Real Estate" },
	{ symbol: "DLR", name: "Digital Realty Trust Inc.", sector: "Real Estate" },
	{ symbol: "VICI", name: "VICI Properties Inc.", sector: "Real Estate" },
	{ symbol: "AVB", name: "AvalonBay Communities Inc.", sector: "Real Estate" },
	{ symbol: "EQR", name: "Equity Residential", sector: "Real Estate" },
	{ symbol: "SBAC", name: "SBA Communications Corp.", sector: "Real Estate" },
	{ symbol: "WY", name: "Weyerhaeuser Company", sector: "Real Estate" },
	{
		symbol: "ARE",
		name: "Alexandria Real Estate Equities",
		sector: "Real Estate",
	},
	{ symbol: "MAA", name: "Mid-America Apartment", sector: "Real Estate" },
	{ symbol: "EXR", name: "Extra Space Storage Inc.", sector: "Real Estate" },
	{ symbol: "IRM", name: "Iron Mountain Inc.", sector: "Real Estate" },
	{ symbol: "ESS", name: "Essex Property Trust Inc.", sector: "Real Estate" },
	{ symbol: "KIM", name: "Kimco Realty Corporation", sector: "Real Estate" },
	{ symbol: "REG", name: "Regency Centers Corporation", sector: "Real Estate" },
	{ symbol: "HST", name: "Host Hotels & Resorts Inc.", sector: "Real Estate" },
	{ symbol: "CPT", name: "Camden Property Trust", sector: "Real Estate" },
	{ symbol: "BXP", name: "BXP Inc.", sector: "Real Estate" },
	{ symbol: "UDR", name: "UDR Inc.", sector: "Real Estate" },
	{ symbol: "VTR", name: "Ventas Inc.", sector: "Real Estate" },
	{ symbol: "PEAK", name: "Healthpeak Properties Inc.", sector: "Real Estate" },
	{
		symbol: "FRT",
		name: "Federal Realty Investment Trust",
		sector: "Real Estate",
	},
	{ symbol: "INVH", name: "Invitation Homes Inc.", sector: "Real Estate" },
	// Materials
	{ symbol: "LIN", name: "Linde plc", sector: "Materials" },
	{ symbol: "APD", name: "Air Products and Chemicals", sector: "Materials" },
	{ symbol: "SHW", name: "The Sherwin-Williams Company", sector: "Materials" },
	{ symbol: "ECL", name: "Ecolab Inc.", sector: "Materials" },
	{ symbol: "FCX", name: "Freeport-McMoRan Inc.", sector: "Materials" },
	{ symbol: "NEM", name: "Newmont Corporation", sector: "Materials" },
	{ symbol: "NUE", name: "Nucor Corporation", sector: "Materials" },
	{ symbol: "DOW", name: "Dow Inc.", sector: "Materials" },
	{ symbol: "DD", name: "DuPont de Nemours Inc.", sector: "Materials" },
	{ symbol: "VMC", name: "Vulcan Materials Company", sector: "Materials" },
	{ symbol: "MLM", name: "Martin Marietta Materials", sector: "Materials" },
	{ symbol: "PPG", name: "PPG Industries Inc.", sector: "Materials" },
	{ symbol: "CTVA", name: "Corteva Inc.", sector: "Materials" },
	{
		symbol: "IFF",
		name: "International Flavors & Fragrances",
		sector: "Materials",
	},
	{ symbol: "BALL", name: "Ball Corporation", sector: "Materials" },
	{ symbol: "CF", name: "CF Industries Holdings Inc.", sector: "Materials" },
	{ symbol: "AVY", name: "Avery Dennison Corporation", sector: "Materials" },
	{ symbol: "EMN", name: "Eastman Chemical Company", sector: "Materials" },
	{ symbol: "ALB", name: "Albemarle Corporation", sector: "Materials" },
	{ symbol: "CE", name: "Celanese Corporation", sector: "Materials" },
	{
		symbol: "PKG",
		name: "Packaging Corporation of America",
		sector: "Materials",
	},
	{ symbol: "IP", name: "International Paper Company", sector: "Materials" },
	{ symbol: "STLD", name: "Steel Dynamics Inc.", sector: "Materials" },
	{ symbol: "MOS", name: "The Mosaic Company", sector: "Materials" },
	{ symbol: "FMC", name: "FMC Corporation", sector: "Materials" },
	{ symbol: "AMCR", name: "Amcor plc", sector: "Materials" },
	{ symbol: "SEE", name: "Sealed Air Corporation", sector: "Materials" },
];
