DROP INDEX "research_notes_tick_idx";--> statement-breakpoint
ALTER TABLE "research_notes" ALTER COLUMN "sentiment" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "research_notes" ALTER COLUMN "symbols" SET DEFAULT '[]'::jsonb;--> statement-breakpoint
ALTER TABLE "research_notes" ALTER COLUMN "symbols" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sim_config" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "research_notes" ADD COLUMN "note_id" varchar(128) NOT NULL;--> statement-breakpoint
ALTER TABLE "research_notes" ADD COLUMN "published_at_tick" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "research_notes" ADD COLUMN "focus" text NOT NULL;--> statement-breakpoint
ALTER TABLE "research_notes" ADD COLUMN "headline" text NOT NULL;--> statement-breakpoint
ALTER TABLE "research_notes" ADD COLUMN "body" text NOT NULL;--> statement-breakpoint
ALTER TABLE "research_notes" ADD COLUMN "confidence" real DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "research_notes" ADD COLUMN "sources" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "research_notes" ADD COLUMN "released_to_tier" "agent_tier" DEFAULT 'research' NOT NULL;--> statement-breakpoint
ALTER TABLE "research_notes" ADD CONSTRAINT "research_notes_note_id_unique" UNIQUE("note_id");--> statement-breakpoint
CREATE INDEX "research_notes_tick_idx" ON "research_notes" USING btree ("published_at_tick");--> statement-breakpoint
ALTER TABLE "research_notes" DROP COLUMN "tick";--> statement-breakpoint
ALTER TABLE "research_notes" DROP COLUMN "title";--> statement-breakpoint
ALTER TABLE "research_notes" DROP COLUMN "content";--> statement-breakpoint
ALTER TABLE "research_notes" DROP COLUMN "release_tick";
